exp_name: pacs_photo_cdane

mode: train
n_classes: 7
method: 'cdan+e'

network:
    arch: resnet18_fc

datasets:
    src:
        type: 'image'
        name: ['cartoon', 'sketch', 'art_painting']
        batch_size: 128
        num_workers: 4
        limit: false
        val_size: 0.1
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    tar:
        type: 'image'
        name: 'photo'
        split: train
        batch_size: 128
        num_workers: 4
        limit: false
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

    test:
        type: 'image'
        name: 'photo'
        split: test
        batch_size: 128
        num_workers: 4
        limit: false
        img_transform:
            jitter: 0
            random_resize_crop:
                size: [222, 222]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

testing:
    model: ''

training:
    resume: ''
    num_print_epoch: 10
    num_epochs: 300
    optimizer:
        name: 'sgd'
        lr: 0.001
        weight_decay: 0.0005
        momentum: 0.9
        nesterov: true
    lr_scheduler:
        name: inv_lr
    transfer_loss_weight: 1.0
