exp_name: office_a_w_uda

mode: train
n_classes: 31
aux_classes: 3
method: 'rotate'

network:
    arch: resnet50_fc

datasets:
    src:
        type: 'rotate'
        name: ['amazon']
        batch_size: 16
        num_workers: 4
        limit: false
        val_size: 0.0
        bias_whole_image: 0.7
        aux_classes: 3
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [224, 224]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    tar:
        type: 'rotate'
        name: 'webcam'
        split: train
        batch_size: 16
        num_workers: 4
        limit: false
        aux_classes: 3
        bias_whole_image: 0.7
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [224, 224]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

    test:
        type: 'rotate'
        name: 'webcam'
        split: test
        batch_size: 16
        num_workers: 4
        limit: false
        aux_classes: 3
        img_transform:
            jitter: 0
            random_resize_crop:
                size: [224, 224]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

testing:
    model: ''

training:
    resume: ''
    num_print_epoch: 10
    num_epochs: 1000
    optimizer:
        name: 'sgd'
        lr: 0.001 # a-w, w-d, w-a, d-a
        # lr: 0.0003 # a-d, d-w
        weight_decay: 0.0005
        momentum: 0.9
        nesterov: true
    lr_scheduler:
        name: inv_lr #step
        # step_size: 24 # num_epochs * 0.8
    src_aux_weight: 0.0
    tar_aux_weight: 0.7
    src_kld_weight: 0.0
    tar_kld_weight: 0.4
    tar_entropy_weight: 0.1
    only_non_scrambled: false
