exp_name: officehome_cl_rw_rot

mode: train
n_classes: 65
aux_classes: 3
method: 'rotate'

network:
    arch: resnet50

datasets:
    src:
        type: 'rotate'
        name: ['Clipart']
        batch_size: 16
        num_workers: 4
        limit: false
        val_size: 0.0
        bias_whole_image: 0.7
        aux_classes: 3
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.222, 0.225]
    tar:
        type: 'rotate'
        name: 'Real_World'
        split: train
        batch_size: 16
        num_workers: 4
        limit: false
        aux_classes: 3
        bias_whole_image: 0.7
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.222, 0.225]

    test:
        type: 'rotate'
        name: 'Real_World'
        split: test
        batch_size: 16
        num_workers: 4
        limit: false
        aux_classes: 3
        img_transform:
            jitter: 0
            random_resize_crop:
                size: [222, 222]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.222, 0.225]

testing:
    model: ''

training:
    resume: ''
    num_print_epoch: 10
    num_epochs: 50
    optimizer:
        name: 'sgd'
        #lr: 0.001 # a-w, w-d, w-a, d-a
        lr: 0.0003 # a-d, d-w
        weight_decay: 0.0005
        momentum: 0.9
        nesterov: true
    lr_scheduler:
        name: step
        step_size: 40 # num_epochs * 0.8
    src_aux_weight: 0.7
    tar_aux_weight: 0.7
    tar_entropy_weight: 0.1
    only_non_scrambled: false
